name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0
  #访问后台
  dio: ^4.0.6
  #数据缓存
  shared_preferences: ^2.0.15
dev_dependencies:
  very_good_analysis: ^3.1.0